name: Terraform validation

on:
  pull_request:
    paths:
      - "infra/**"
  push:
    branches: [master]
    paths:
      - "infra/**"

jobs:
  validate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3
      - run: terraform init -backend=false
      - run: terraform validate
